using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GlobalConstants : MonoBehaviour
{

    public const string MUSIC_VOLUME = "musicVolume";
    public const string SOUND_VOLUME = "soundVolume";
    public const string HIGH_SCORE = "highScore";
    public const string GOLD_GEM_PRIZE = "goldGemPrize";
    public const string PURPLE_GEM_PRIZE = "purpleGemPrize";
    public const string GOLD_MEDAL = "goldMedal";
    public const string SILVER_MEDAL = "silverMedal";
    public const string BRONZE_MEDAL = "bronzeMedal";

    public const string MUSIC_VOLUME_KEY = "musicVolumeKey";
    public const string SOUND_VOLUME_KEY = "soundVolumeKey";
    public const string LEVELS_COMPLETE_KEY = "levelscompletekey";
    public const string TUT_LEVELS_COMPLETE_KEY = "tutlevelscompletekey";
    public const string CONTROLLER_KEY = "ControllerKey";
    public const string NUMBER_OF_LEVELS = "NumberOfLevels";
    public const string NUMBER_OF_TUT_LEVELS = "NumberOfTutLevels"; 

    public const string MUSIC_1 = "Virgo";
    public const string MUSIC_2 = "Beta Testing";
    public const string MUSIC_3 = "Childhood Memories";
    public const string MUSIC_4 = "Creepy";
    public const string MUSIC_5 = "Dark Drama";
    public const string MUSIC_6 = "Dark Thrill";
    public const string MUSIC_7 = "Dawn";
    public const string MUSIC_8 = "Enigmatic";
    public const string MUSIC_9 = "Epic";
    public const string MUSIC_10 = "Fast";
    public const string MUSIC_11 = "Finding Justice";
    public const string MUSIC_12 = "Gauntlet";
    public const string MUSIC_13 = "Haunting";
    public const string MUSIC_14 = "Heartbeat";
    public const string MUSIC_15 = "Howling Wind";
    public const string MUSIC_17 = "Inferno";
    public const string MUSIC_18 = "Island";
    public const string MUSIC_19 = "Life";
    public const string MUSIC_20 = "Moments";
    public const string MUSIC_21 = "No Place";
    public const string MUSIC_22 = "No Time";
    public const string MUSIC_23 = "Pleasant Pastures";
    public const string MUSIC_24 = "Pounding";
    public const string MUSIC_26 = "Suspense";
    public const string MUSIC_27 = "Sweet";
    public const string MUSIC_28 = "The Harder They Fall";
    public const string MUSIC_29 = "Thinking";
    public const string MUSIC_30 = "Under Cover";
    public const string MUSIC_31 = "Virgo";
    
    public const string LEVEL_1 = "Gem Collecting";
    public const string LEVEL_2 = "Simple";
    public const string LEVEL_3 = "Stairs";
    public const string LEVEL_4 = "Scitter Scatter";
    public const string LEVEL_5 = "Shapes";
    public const string LEVEL_6 = "Cave In";
    public const string LEVEL_7 = "Rollers From Hell";
    public const string LEVEL_8 = "Temple";
    public const string LEVEL_9 = "Consume";
    public const string LEVEL_10 = "Back to the Beginning";
    public const string LEVEL_11 = "Tele Collect";
    public const string LEVEL_12 = "Shrapnel";
    public const string LEVEL_13 = "Divided";
    public const string LEVEL_14 = "Explode";
    public const string LEVEL_15 = "Constructs";
    public const string LEVEL_16 = "Down We Go";
    public const string LEVEL_17 = "Slider";
    public const string LEVEL_18 = "Lever";
    public const string LEVEL_19 = "Dodger Field";
    public const string LEVEL_20 = "Coniption";
    public const string LEVEL_21 = "It's Raining";
    public const string LEVEL_22 = "Falling Bridges";
    public const string LEVEL_23 = "Tele Maze";
    public const string LEVEL_24 = "Balance Beams";
    public const string LEVEL_25 = "Consumer City";
    public const string LEVEL_26 = "Demolition Gauntlet";
    public const string LEVEL_27 = "Suspended";
    public const string LEVEL_28 = "Warehouse";
    public const string LEVEL_29 = "Jumpy";
    public const string LEVEL_30 = "Omg";
    public const string LEVEL_31 = "Holy Cow";
    public const string LEVEL_32 = "Mines";
    public const string LEVEL_33 = "Traps";
    public const string LEVEL_34 = "=)";
    public const string LEVEL_35 = "Race";
    public const string LEVEL_36 = "Push Blocks";
    public const string LEVEL_37 = "Towers";
    public const string LEVEL_38 = "Labyrinth";
    public const string LEVEL_39 = "The Chase";
    public const string LEVEL_40 = "Ballerina";
    public const string LEVEL_41 = "Ball Pool";
    public const string LEVEL_42 = "Tippy";
    public const string PRE_SPLASH = "Pre Splash";
    public const string SPLASH_SCREEN = "Splash Screen";
    public const string MAIN_MENU = "Main Menu";
    public const string OPTIONS_MENU = "Options Menu";
    public const string PAUSE_MENU = "Pause Menu";
    public const string LEVEL_MENU = "Level Menu";
    public const string LEVEL_TITLE = "Level Title";
    public const string TIPS_MENU = "Tips Menu";
    public const string HIGHSCORES_MENU = "Highscores Menu";
    public const string TUTLVL_0 = "Tutorial Level 0";
    public const string TUTLVL_1 = "Tutorial Level 1";
    public const string TUTLVL_2 = "Tutorial Level 2";
    public const string TUTLVL_3 = "Tutorial Level 3";
    public const string TUTLVL_4 = "Tutorial Level 4";
}
